### ISSUE TITLE
Hardware ?

### ISSUE THREAD

**Issue by Aorlhac** [Domochip/WirelessPalaControl#1]
Hello, do you still have some PCB and box left ? i'm very interested 👍

**Comment by Domochip** [comment]
Yes, you can contact me directly at domochip[@]hotmail.com

**Comment by djpostka** [comment]
Hello,

I will also wish to buy a pcb if possible. thank you.

**Comment by Domochip** [comment]
@djpostka I just found your email into junks, I'm replying directly through mail

**Comment by nargotik** [comment]
HI @Domochip just sent you and email to check if you still have some kits

**Comment by Domochip** [comment]
Hi, Yes, I have, let's continue by mail :-)

**Comment by starship666** [comment]
Hi @Domochip, can't find your email but I'm also interested if you still have some kits to try it.

**Comment by frisk2** [comment]
Hello, do you still have some PCB and box left ? i'm interested.

**Comment by Domochip** [comment]
Hi, Yes, I have, let's continue by mail :-)
domochip[@]hotmail.com

**Comment by Domochip** [comment]
closing this issue because tindie product is now available: https://www.tindie.com/products/domochip/wirelesspalacontrol-aka-wpalacontrol/
