### ISSUE TITLE
Compatibility with ET4W control

### ISSUE THREAD

**Issue by mattiabrunello5** [Domochip/WirelessPalaControl#13]
Hi, is hass-palazzetti compatible with et4w control ( for fan speed and combustion?

Thanks for answer

**Comment by mattiabrunello5** [comment]
hi i make a mistake, sorry, (haas-palazzetti si another repository )

ET4W is another controller of palazetti for control of fireplaces, its work on wifi, i link above a page for more info:
https://palazzettigroup.com/research-and-development/technology/

**Comment by Domochip** [comment]
Does Easytech4wood is embedded into the stove or this is an option?

**Comment by mattiabrunello5** [comment]
Is an option for pellet stove 
Wood stove 
And fireplace

**Comment by Domochip** [comment]
Then it depends of the motherboard, if it matches with the one in WPalaControl description then it will work otherwise I'll need more info of the new motherboard.
Description: https://github.com/Domochip/WirelessPalaControl#compatibility

**Comment by mattiabrunello5** [comment]
This is a link of the manual of this interface 

https://cdn.palazzetti.it/manuals/004779060.pdf

**Comment by Domochip** [comment]
I was talking about the stove motherboard

**Comment by mattiabrunello5** [comment]
I don't have the possibility to check  ,but maybe it's the same ?

**Comment by mattiabrunello5** [comment]
I noticed a electric wiring Diagram il this pdf

https://cdn.palazzetti.it/manuals/004778071.pdf

https://cdn.palazzetti.it/manuals/004777731.pdf

**Comment by Domochip** [comment]
Sorry, but no docs give enough about the motherboard.
I can't ensure that WPalaControl willl be able to connect to it.

**Comment by mattiabrunello5** [comment]
ok thanks
