### ISSUE TITLE
Configuration and infos on TIMER status

### ISSUE THREAD

**Issue by 1300371** [Domochip/WirelessPalaControl#15]
Hello,

I've got a Palazzetti stove and there is a TIMER fonction that you have to turn on if you want to schedule ON/oFF.

Is there a way to get that _TIMER status_ and also to set it ?

Here is a video of the feature: https://www.youtube.com/watch?v=YBgKCtgVSOY

**Comment by Domochip** [comment]
Hi, I never used it, but I think this is `Chrono Data`/`Chrono Status` that you are looking for.
And `Chrono Program` is the way to configure its planning.

**Comment by 1300371** [comment]
BTW, is it possible to forward more data via mqtt ? All these data are availble only via http ? 😕

**Comment by 1300371** [comment]
Ping @Domochip

**Comment by 1300371** [comment]
Did read you my second question @Domochip ? Sorry for spam

**Comment by Domochip** [comment]
Hello,
Sorry for the very very late reply.
The new V3.0.0 (just released) allows you to get this info via MQTT if you send "GET+CHRD" to cmd topic.
Could you give it a try and let me know if it matches to your needs?

**Comment by 1300371** [comment]
No problem.  
To update, just have to upload the _bin_ firmware file througth the UI ?

**Comment by Domochip** [comment]
yes

**Comment by Domochip** [comment]
Ping @1300371

**Comment by 1300371** [comment]
Sorry 😅
As this is winter in France, I want to wait spring to not jeopardize my installation (in case of something goes wrong)
