### ISSUE TITLE
[Question] Set date/time

### ISSUE THREAD

**Issue by davidlevillain** [Domochip/WirelessPalaControl#17]
I would like to set date/time automatically using my home assistant. Is it possible to set stove date and time using MQTT/HTTP commands ?

**Comment by Domochip** [comment]
I'm currently working on multiple improvements and this one is part of it.
It will be released soon

**Comment by Domochip** [comment]
Hello,

V3.0.0 (released today) offers the SET TIME command through MQTT and HTTP
