### ISSUE TITLE
Stove infos

### ISSUE THREAD

**Issue by Ir0n42** [Domochip/WirelessPalaControl#18]
Hi, I have received my controller with 1.4.1 system running.
I have configured it on my network and plug RJ11 on my Palazzetti Monica. 
But now, stove info still empty, why? Forgot something? 
Thank you

**Comment by Domochip** [comment]
Hi, 
Could you provide a screenshot of the complete version number.
maybe a picture of the cabling to the stove too.

Thanks

**Comment by Ir0n42** [comment]
Yes sure! 
![Uploading 97B386A4-6BAB-4EED-9DDF-948B14A84888.jpeg…]()

**Comment by Ir0n42** [comment]
![D627C5E2-B807-40A8-9413-6B3047DA3ACB](https://user-images.githubusercontent.com/28147078/230474599-84ae12fa-ca66-40f7-8518-80ec4d436220.jpeg)
![8E33F210-3241-4C4A-9FB1-ED9FD8C5EB14](https://user-images.githubusercontent.com/28147078/230474603-71160951-f349-4e99-ae45-e5d544f20490.jpeg)
![5EA2D8DB-FA62-48FE-B22E-C4F99661E99A](https://user-images.githubusercontent.com/28147078/230474604-e3b5ef5c-f8d4-422a-8a23-caacb845d35f.jpeg)

**Comment by Ir0n42** [comment]
![Uploading C96A8E17-DF64-4DAE-9256-6EED3C5654E1.jpeg…]()

**Comment by Ir0n42** [comment]
![15DD6998-7504-410D-877C-CE3B9950D5ED](https://user-images.githubusercontent.com/28147078/230474881-6ecec78c-8acb-452f-9b33-dab8f4b6f9b5.jpeg)
![6692C573-FB4E-46AD-8D65-DD51406B6A83](https://user-images.githubusercontent.com/28147078/230474885-e31f5fc4-5d3b-42d8-ae67-1028c6c9c080.jpeg)

**Comment by Ir0n42** [comment]
![Uploading D22D207B-CF5C-4F3B-B3B8-6D90F3F0F87A.jpeg…]()

**Comment by Ir0n42** [comment]
![250D8AB6-5C64-4775-B8D6-FF9C8A5C4500](https://user-images.githubusercontent.com/28147078/230474969-c22d5185-35a4-4834-ac1b-4ccb22860254.jpeg)

**Comment by Ir0n42** [comment]
![Uploading 63EA6B6D-D54F-4FF6-88C7-643DC2CC7C92.jpeg…]()

**Comment by Ir0n42** [comment]
![0E1007E1-14A9-4116-A614-592252EBE4B7](https://user-images.githubusercontent.com/28147078/230475082-46f35cc0-42db-45f3-bca2-825349f54cee.jpeg)

**Comment by Domochip** [comment]
OK, 
First I advise to update to the last firmware version.
Next to this one, you should see serial number on the landing page.
With your current version, even if nothing appears, it doesn't mean the module doesn't work.
You can try to query this URL to check : http://**{IP}**/cgi-bin/sendmsg.lua?cmd=GET+STDT

**Comment by Ir0n42** [comment]
Ok thank you, I have update it. 
Message :
 Stove infos (07/04/2023 10:02:30)
    MSG : Stove communication failed! please check cabling to your stove.
And when I Go to http://{IP}/cgi-bin/sendmsg.lua?cmd=GET+STDT
Message : 
{"INFO":{"CMD":"GET STDT","MSG":"Stove communication failed","RSP":"TIMEOUT"},"SUCCESS":false,"DATA":{"NODATA":true}}

**Comment by Domochip** [comment]
It seems you have an issue with the cabling.
Does the cable match with the image here ? : https://github.com/Domochip/WirelessPalaControl#connect

**Comment by Ir0n42** [comment]
Yes ! It's crossed

**Comment by Domochip** [comment]
Then, do you have a picture of your stove motherboard?

**Comment by Ir0n42** [comment]
I will open it

**Comment by Ir0n42** [comment]
That enouth for you? 
![Uploading F349A479-4C50-4215-ADFB-769DBD368CD2.jpeg…]()

**Comment by Ir0n42** [comment]
@
![Uploading 18DE64C0-0DCA-4E64-BA39-E1F6593D57F0.jpeg…]()

**Comment by Ir0n42** [comment]
![Uploading BB2FE962-0CBC-43A3-BE78-15FA04A11DB2.jpeg…]()

**Comment by Ir0n42** [comment]
![8FEE2CFB-51B6-44CE-A649-59455E90B815](https://user-images.githubusercontent.com/28147078/230575968-99f6c745-ade9-4a20-9d49-0150b7cccc8e.jpeg)

**Comment by Domochip** [comment]
Yes, defenitly!
This is a MicroNova motherboard and WirelessPalaControl is **NOT** compatible with MicroNova.
As per written in first chapters (https://github.com/Domochip/WirelessPalaControl), this project aims to control Fumis based stoves.
Your stove should be pretty old to have this kind of Motherboard.

I let you contact me by mail for further discussion.
