### ISSUE TITLE
Palazzetti Margot

### ISSUE THREAD

**Issue by CrazYoshi** [Domochip/WirelessPalaControl#19]
Hi,
I have a Palazzetti Margot stove.
I would like to control it using HomeAssistant.
Is it your adapter compatible with this stove? 
I see there is a serial port available on the back. Is it possible to use it to connect the device?
Thanks

**Comment by Domochip** [comment]
Hi,

I never seen this kinfd of model.
The only way to confirm is to open it and verify what is the motherboard brand.
