### ISSUE TITLE
esphome / Home assistant

### ISSUE THREAD

**Issue by PetitJean74230** [Domochip/WirelessPalaControl#20]
Hello, would it be possible to adapt this project on an ESPhome module and implement it to Home Assistant?

**Comment by Domochip** [comment]
hello,
Adapting it to ESPHome would require a too big effort for me.
regarding Home Assistant, you can use this custom integration : https://github.com/marcopal74/home-assistant-palazzetti
As WPalaControl reacts like ConnectionBox, it works.

**Comment by PetitJean74230** [comment]
thanks
