### ISSUE TITLE
Which SI8621 chip?

### ISSUE THREAD

**Issue by dxmen7** [Domochip/WirelessPalaControl#26]
Hello everyone,
I'm looking for the right SI8621 chip for the Palacontrol. At LCSC I have different ordering part numbers and different output states. Actually, I'm thinking of three different chips: Si8621BB-B-IS, Si8621BC-B-IS, Si8621EC-B-IS. First both have LOW output state, the third one HIGH output state. Does it have any effect for the palacontrol?
Thanks!

**Comment by Domochip** [comment]
Hi,

The original design is using an Si8621**EC**
