### ISSUE TITLE
Add F3L and F4L setting

### ISSUE THREAD

**Issue by carmelo42** [Domochip/WirelessPalaControl#33]
Just tried the 2.1.5/3.1.2v2 pre-release : 

![image](https://github.com/Domochip/WirelessPalaControl/assets/2070041/3b96eacc-fe63-4098-b171-509c0d35a0d1)

It works great :) 

I can change the main fan setting (F3L) but there are 2 settings missing : left and right fans (F3L and F4L) : 

<img width="351" alt="image" src="https://github.com/Domochip/WirelessPalaControl/assets/2070041/dbd8d87e-5af3-4357-9adb-1a662e42a4d2">

**Comment by Domochip** [comment]
Thank you for the feedback.
I had a doubt about this part because my stove doesn't have this additionnal fans.
So, if I understand well, it would be better to have 2 sliders for F3 and F4, right? With value from 0 to 5?

**Comment by carmelo42** [comment]
Yes exactly :) 
2 sliders for the 2 additional fans, scale 0 to 5.

**Comment by pm2036** [comment]
Hello, 
On my stove, F3L and F4L is only 0/1. Maybe it depends of the stove model?

![Screenshot_2024-02-09-10-01-37-662_it palazzetti app smartstoves-edit](https://github.com/Domochip/WirelessPalaControl/assets/1732698/d850fde9-dea8-4251-874b-e11eac67c927)
![Screenshot_2024-02-09-10-02-06-744_it palazzetti app smartstoves-edit](https://github.com/Domochip/WirelessPalaControl/assets/1732698/1d91f288-3861-4891-bbd6-28145e5e25ed)

**Comment by carmelo42** [comment]
Mine is "TURBOFONTE TAL" which is I think the same as PALAZZETTI JULIA : 

```
// 20240209100452
// http://192.168.0.239/cgi-bin/sendmsg.lua?cmd=SET+FN4L+4

{
  "INFO": {
    "CMD": "SET FN4L",
    "RSP": "OK"
  },
  "DATA": {
    "F4L": 4
  },
  "SUCCESS": true
}
```
On the MQTT bus : 
<img width="88" alt="image" src="https://github.com/Domochip/WirelessPalaControl/assets/2070041/2d018832-b5c5-49e1-b05b-913131d166b2">

And for the other fan : 
```
// 20240209100713
// http://192.168.0.239/cgi-bin/sendmsg.lua?cmd=SET+FN3L+4

{
  "INFO": {
    "CMD": "SET FN3L",
    "RSP": "OK"
  },
  "DATA": {
    "F3L": 4
  },
  "SUCCESS": true
}
```
<img width="81" alt="image" src="https://github.com/Domochip/WirelessPalaControl/assets/2070041/6d4ec9ef-dfc9-4822-8d80-41ad86ba54fd">

**Comment by pm2036** [comment]
Ok, mine is a Palazzetti Allegro

`http://192.168.110.70/cgi-bin/sendmsg.lua?cmd=SET+FN3L+4`
`{"INFO":{"RSP":"OK","CMD":"SET FN3L","TS":1707471245},"SUCCESS":true,"DATA":{"F3L":1}}`

I think the max value is in sendmsg.lua?cmd=GET+ALLS
"FANLMINMAX":[0,5,0,1,0,1]

**Comment by Domochip** [comment]
Yes, FANLMINMAX contains these limits.
2 firsts numbers are min and max for RoomFan (aka FAN2)
2 nexts are for F3
then 2 last numbers are for F4

So, the good option id to use some switches for stove which have "0,1" limits and sliders for "0,5" limits
I'll implement that shortly

**Comment by Domochip** [comment]
V3 prerelease is available and adjust the HomeAssistant Entity type based on the Fan Min and Max values.
Could you let me know if it fit your needs?

**Comment by carmelo42** [comment]
It works great :) 

![image](https://github.com/Domochip/WirelessPalaControl/assets/2070041/31e2df6d-d4bd-45ea-b9c1-0d8db2f15aca)

**Comment by Domochip** [comment]
In your case, switch buttons can be removed then

**Comment by carmelo42** [comment]
Yes I will remove them. 
I'm happy, I've removed https://github.com/marcopal74/home-assistant-palazzetti which was not working every time.

**Comment by pm2036** [comment]
Ok for me too, thanks.
![image](https://github.com/Domochip/WirelessPalaControl/assets/1732698/61fd4664-1831-4e96-8d59-a5fc730b9d9e)
