### ISSUE TITLE
SET+PWR+2 sent instead of SET+POWR+2

### ISSUE THREAD

**Issue by carmelo42** [Domochip/WirelessPalaControl#34]
Hello,

From HA, when is use the slider to set fire power to 2, the command sent is SET+PWR+2 instead of SET+POWR+2 so it doesn't change the value:

<img width="568" alt="image" src="https://github.com/Domochip/WirelessPalaControl/assets/2070041/f002cbe9-2604-4567-b6cf-9cb5551230fd">

If I send the correct command through HTTP it's ok: 
```
// 20240211090505
// http://192.168.0.239/cgi-bin/sendmsg.lua?cmd=SET+POWR+2

{
  "INFO": {
    "CMD": "SET POWR",
    "RSP": "OK"
  },
  "DATA": {
    "PWR": 2,
    "F2L": 2,
    "FANLMINMAX": [
      0,
      5,
      0,
      5,
      0,
      5
    ]
  },
  "SUCCESS": true
}
```

**Comment by Domochip** [comment]
thx, I republished the v3 prerelease with to fixed topic

**Comment by carmelo42** [comment]
Flashed, and it works fine :)
Thanks a lot :)
