### ISSUE TITLE
Stove communication failed

### ISSUE THREAD

**Issue by 1300371** [Domochip/WirelessPalaControl#41]
I use WPalaControl since 3 years now without issues.

Usually, i unplugged (from electric power) the stove and WPala module from winter to automn. 
I replugged recently my setup and saw that WPalaControl failed to communicate with stove.

My tries until then:
- check/switch cable
- update firmware from 1.4.1 to 2.2.2

When i plugged the stove to the module, some LED lights up but WPalaControl indicates:
`MSG : Stove communication failed! please check cabling to your stove.`

I changed nothing from last usage...

Is there a way to check logs from WPalaControl ? It's like the module can communicate with stove but info from stove are kind of wrong.

**Comment by Domochip** [comment]
If you connect the module to the stove without powering it (micro-usb disconnected), do you see the D1 led blinking (next to the RJ11 connector)?

**Comment by 1300371** [comment]
Yes

**Comment by Domochip** [comment]
The log is going out to the pin D4 on d1_mini. That means you need to solder a cable to a separate serial adapter.

**Comment by Domochip** [comment]
otherwise, if you have an ESP32 miniKit like this : 
![image](https://github.com/user-attachments/assets/6244ea2a-7414-48bc-ab31-30a9777928d2)
Then you can get the log directly to the usb serial of the module

**Comment by 1300371** [comment]
I use this

![unnamed](https://github.com/user-attachments/assets/8bb26041-461e-4c35-9183-030456e0d6eb)
![unnamed (1)](https://github.com/user-attachments/assets/55072d7f-e3a5-4e6d-a0fc-c90eea5c47a9)
![unnamed (2)](https://github.com/user-attachments/assets/5a45d8e2-9565-43f9-8111-94183f776710)
![unnamed (3)](https://github.com/user-attachments/assets/bc003c7a-24f8-4d26-9f81-bb4876961664)
![unnamed (4)](https://github.com/user-attachments/assets/e6efe956-551b-4962-af48-24148bed0da3)

**Comment by Domochip** [comment]
I advise you to check soldering of U1 maybe for a bad contact.
It is usually the difficult point where I'm finally cheking with microscope

**Comment by 1300371** [comment]
![WIN_20240908_21_08_19_Pro](https://github.com/user-attachments/assets/1558fd92-6365-4065-960e-3bc20c25ca82)

Maybe the issue ... Will try to resolder 🤞

**Comment by 1300371** [comment]
Tricky to sold ... but i was that !!
![image](https://github.com/user-attachments/assets/9cd310fa-b9b3-4444-99d9-f80ea3390c74)
Thank you so much ❤️

**Comment by Domochip** [comment]
yw 😉
