### ISSUE TITLE
Aide: Home Assistant Discovery

### ISSUE THREAD

**Issue by Gamodeur** [Domochip/WirelessPalaControl#43]
Bonjour,

Merci beaucoup pour votre excellent projet.
De mon côté, j’ai effectué toute l’installation et tout fonctionne bien, sauf le « Home Assistant Discovery ».

Si j’ai bien compris, le « Home Assistant Discovery » permet de remonter automatiquement les entités dans Home Assistant ?

En revanche, j’arrive à bien configurer une entité en l’ajoutant manuellement dans le fichier de configuration.

Est-ce que l’option « Base Topic » a un impact sur ce paramètre ?

(Build version : 2.2.2/3.1.3)

Ma config: 
![image](https://github.com/user-attachments/assets/c333f83e-fec3-47f8-94c2-deade9be100e)

Version Home Assistant:
![image](https://github.com/user-attachments/assets/aa9683f6-d079-446d-8c13-8aae29eff541)

Version Mosquitto broker: 6.4.1

**Comment by Domochip** [comment]
Première question : Est-ce que le module se connecte bien au poele et au broker MQTT?
(le numéro de série apparait et l'état est Connected)
![image](https://github.com/user-attachments/assets/d6079ab8-2da9-4840-94c8-c58e559a0c96)

Pour répondre aussi à votre question : Est-ce que l’option « Base Topic » a un impact sur ce paramètre ?
Non, cela n'a pas d'impact, les données d'autodiscovery pour Home Assistant sont mise à jour si cette valeur change.

**Comment by Gamodeur** [comment]
J'ai pas de numéro de série par contre.
![image](https://github.com/user-attachments/assets/e907a91f-bd9e-478e-85bf-303e57ba7cd4)

![image](https://github.com/user-attachments/assets/7b25ece5-442d-41b9-903d-4ad22c624c62)

Donner visible avec MQTT Explorer
![image](https://github.com/user-attachments/assets/22cce9cd-e7b4-4615-89ae-8723f5344823)

**Comment by Domochip** [comment]
OK, la partie qui va m'intéresser maintenant, c'est ce qu'il y a dans les topics sous homeassistant : 
![image](https://github.com/user-attachments/assets/f0f1af3b-879d-48b2-876e-7e80adf12713)
Les premières entités publiées sont celles-ci. L'une correspond à l'état de connexion du module WPalaControl et la seconde à l'état de connexion du poêle. Sont-elles présentes?

**Comment by Gamodeur** [comment]
J'ai rien qui correspond au module WPalaControl

**Comment by Domochip** [comment]
ok, je vois.
Je vérifie que le numéro de série est valide avant d'envoyer l'autodiscovery.
Et là, le numéro de série est 00...00
Je vais enlever ce contrôle.
Par curiosité, de quelle marque et modèle de poêle s'agit-il?

**Comment by Domochip** [comment]
Chez Palazzetti, le numéro de série commence par LT[année de fabrication} puis des chiffres.
Est-ce que le numéro de série JOTUL suit ce format?
Je pense surtout que JOTUL met les cartes Fumis dans les poeles et ne programme pas le numéro de série ensuite, tout simplement 😄

**Comment by Gamodeur** [comment]
Oui mon numéro de série commence par LT2015
Après sur l'étiquette arrière il nomme ça "Matr N." et non "SN"

Oui je pense aussi et ça m'étonnerait pas 😄
