### ISSUE TITLE
Découvert impossible dans Home Assistant

### ISSUE THREAD

**Issue by Archange2222** [Domochip/WirelessPalaControl#45]
Bonjour

J'ai correctement configuré l'ESP et la connexion avec Home Status est OK

> Home Automation Status
> MQTT Connection State : Connected
> Last Publish Result : OK

Cependant Home Assistant ne le détecte pas automatiquement : 

Mosquitto broker : 6.4.1 
Home Assistant : 
> Core 2024.9.2
> Supervisor 2024.09.1
> Operating System 13.1
> Interface utilisateur 20240909.1

Merci

<img width="719" alt="image" src="https://github.com/user-attachments/assets/0072874f-4706-413c-9055-c521a2f0a254">

**Comment by Domochip** [comment]
Bonjour,

Pourriez-vous me confirmer que le numéro de série du Poêle apparait sur la page de status (même si ce ne sont que des 0 pour Jotul): 
![image](https://github.com/user-attachments/assets/538049d1-30a6-451e-9dd3-9058de01edbd)


Il faut ensuite utiliser "MQTT Explorer" et jeter un œil à ces topics (sont-ils présents):
![image](https://github.com/user-attachments/assets/7e8a5666-5476-44ad-a186-4085ab2c5405)

Bonne Soirée

**Comment by Archange2222** [comment]
Bonsoir 

Le numero de serie apparaît bien 

![DE124353-3757-4912-9611-AD07E9C65955_1_201_a](https://github.com/user-attachments/assets/51f2439e-81b8-4ecf-bf12-374afc5a1d6b)

Dans MQTT explorer j'ai cela :

![image](https://github.com/user-attachments/assets/cc8ce07e-ee4c-4259-8284-082543792bd0)

**Comment by Domochip** [comment]
Bonjour,

Dans MQTT Explorer, c'est la partie dans **homeassistant** qui m'intéresse

**Comment by Domochip** [comment]
Bonsoir,

Votre problème est-il résolu? Sinon, pourriez-vous me transmettre une capture de la partie **homeassistant** dans MQTT Explorer comme sur ma capture : 
![image](https://github.com/user-attachments/assets/11d8f07d-8575-4c30-9ea4-0cd4c65bcafe)

**Comment by Archange2222** [comment]
Bonsoir, 

pardon, voilà le bon imprim écran 

![image](https://github.com/user-attachments/assets/4b18560d-c960-4a8b-89f4-698119f5c35d)

**Comment by Domochip** [comment]
ok, le module envoie donc correctement les infos à homeassistant.
Est-ce que les appareils sont bien apparus dans Home Assistant comme ceci (WPalaControl et Stove) : 
![image](https://github.com/user-attachments/assets/4c25f604-96c6-4afe-b612-b2825cce6432)

**Comment by Archange2222** [comment]
Bonjour 

c’est bon il apparaît bien correctement, j’étais persuadé qu’il fallait faire un ajout manuel comme un nouvel appareil. Mais c’est bon il remonte bien et j’ai bien toutes les informations. 

Merci pour votre aide et bonne journée
