### ISSUE TITLE
Not responsive after some time

### ISSUE THREAD

**Issue by ec0li82** [Domochip/WirelessPalaControl#50]
Hello
For the second time, my WirelessPalaControl became unresponsive. This time it's after 4 days. Latest firmware.
Not available/disconnected in ha
Web gui not responding
IP not pinging
RJ11 led stays red as normal
Only solution is replug USB power.

I'm wondering if it's DHCP (ip set in DHCP server)...I've set a static IP directly now...let's see.
Wondering about my USB power source, will change that next time...
How to troubleshoot further?
Thanks.

**Comment by Domochip** [comment]
If there is no wifi connection, the module switch automatically to AccessPoint mode.
An interesting thing would be to go close to the module and see if the Wifi network named "WirelessPalaControlXXX" appears

**Comment by ec0li82** [comment]
Happened again after 12 hours.
Was not in ap mode.
I've now changed the USB plug and cable. Let's see

**Comment by ec0li82** [comment]
Seems stable now... Let's close
