### ISSUE TITLE
Wifi backup?

### ISSUE THREAD

**Issue by Flobul** [Domochip/WirelessPalaControl#7]
Sometimes, I reboot my wi-fi router and the Wpalacontrol does not reconnect to my router, it creates its own AP, and never try to reconnect. So I have to reset it manually. I notice only when I try to launch manually... So maybe a few days later.

Maybe adding a second SSID network (fallback)? I the first is unreachable, try the other one?
Or maybe a watchbog: if in AP because SSID network was unreachable, retry in 5 minutes?

**Comment by Domochip** [comment]
Very strange, WirelessBase should look back for configured SSID every 60sec (during 20sec).
It does only if there is NO Client currently connected to the AP.
Is it your case?

**Comment by Flobul** [comment]
No client connected to the WpalaControl AP.

**Comment by carmelo42** [comment]
Same here, when the router is restarted, I can see the the Wpalacontrol AP, but even if no client is connected it does not reconnect to my router. I have to reboot Wpalacontrol.

**Comment by Domochip** [comment]
please, ensure that no laptop or mobile phone connect to the module

**Comment by carmelo42** [comment]
Yes, you were right ... I've forgotten a laptop used once to configure the module , my bad !
Sorry for the noise.

**Comment by Flobul** [comment]
Nevermind, an old phone I used to configure WPalaControl was connecting to it...
